In [1]:
import pandas as pd

In [2]:
csv_filename = '/Users/sam/Downloads/Double Crux Questionnaire (Responses) - Form responses 1(5).csv'

In [3]:
pd.read_csv(csv_filename, index_col='Name')

,Timestamp,"""If my country asked me to fight a war, I would.""","""It's sometimes necessary to censor books.""","""It's OK to burn a country's flag.""","""While swimming with an old friend and a new, promising friend, they both start to struggle. If I can pick only save one I should pick the old friend.""","""Someone employs ten people in a struggling business. They should fire their employees rather than commit tax fraud.""","""If my family member committed a crime, I would lie to cover for them.""","""Monogamous relationships are better than polyamorous ones.""","""I have a moral duty to avoid eating meat.""","""It's worth people today working full-time to prevent AI causing human extinction.""","""Schools should be able to mandate uniforms."""
Name,,,,,,,,,,,
Priyansha,23/07/2022 20:42:09,4,1,4,5,4,7,7,4,7,5
Silas,23/07/2022 20:53:38,2,2,7,6,4,5,5,2,7,7
Maia,23/07/2022 20:53:41,5,2,7,5,6,3,2,6,6,4
Søren Elverlin,23/07/2022 20:53:52,5,5,7,5,7,5,4,2,7,4
Roger Curley,23/07/2022 20:54:09,5,2,7,5,6,5,5,3,7,4
Phil,23/07/2022 20:54:16,3,5,7,5,5,2,2,5,7,6
Kayla,23/07/2022 20:54:17,5,3,6,6,6,6,3,1,5,6
Vishal,23/07/2022 20:54:34,6,7,6,4,7,5,6,5,6,7
Francisco,23/07/2022 20:54:45,1,1,7,4,2,5,5,6,6,7
Sam Celarek,23/07/2022 20:54:46,3,5,6,7,6,6,5,6,6,5
Sky,23/07/2022 20:54:47,3,2,5,7,6,4,2,1,6,6
Anastasia,23/07/2022 20:54:51,2,1,7,1,4,2,2,5,6,2
Shoshannah Tekofsky,23/07/2022 20:54:53,3,6,7,1,4,4,4,4,7,1
Jonathan Ray,23/07/2022 20:54:58,4,1,4,6,4,6,4,2,7,7
Emmett,23/07/2022 20:55:24,2,2,2,4,6,2,4,2,6,7
Samuel,23/07/2022 20:55:32,2,2,5,5,6,3,5,5,7,5
Harold,23/07/2022 20:55:37,4,3,7,4,2,5,3,1,3,6
Chris Watkins,23/07/2022 20:55:58,2,3,6,4,5,2,3,5,7,5
Max,23/07/2022 20:56:47,6,2,7,6,6,5,5,5,7,6

In [4]:
def biggest_difference(row1, row2):
    return (row1-row2).abs().max()

In [5]:
def build_distance_matrix(response_df, metric=biggest_difference):

    distance_matrix = pd.DataFrame(index=response_df.index,
                                   columns=response_df.index)

    for idx, row in response_df.iterrows():
        for idy, col in response_df.iterrows():        
            distance_matrix.loc[idx, idy] = metric(row, col)

    return distance_matrix

In [6]:
dm = build_distance_matrix(
        pd.read_csv(csv_filename, index_col='Name'
               ).drop('Timestamp', axis='columns'
                     )
).apply(pd.to_numeric)
dm

Name,Priyansha,Silas,Maia,Søren Elverlin,Roger Curley,Phil,Kayla,Vishal,Francisco,Sam Celarek,Sky,Anastasia,Shoshannah Tekofsky,Jonathan Ray,Emmett,Samuel,Harold,Chris Watkins,Max
Name,,,,,,,,,,,,,,,,,,,
Priyansha,0,3,5,4,3,5,4,6,3,4,5,5,5,3,5,4,4,5,3
Silas,3,0,4,3,3,3,3,5,4,4,3,5,6,3,5,3,4,3,4
Maia,5,4,0,4,3,3,5,5,4,3,5,4,4,4,5,3,5,3,3
Søren Elverlin,4,3,4,0,3,3,2,3,5,4,3,4,4,4,5,3,5,3,3
Roger Curley,3,3,3,3,0,3,2,5,4,3,3,4,4,3,5,3,4,3,2
Phil,5,3,3,3,3,0,4,4,4,4,4,4,5,4,5,3,4,2,3
Kayla,4,3,5,2,2,4,0,4,5,5,2,5,5,2,4,4,4,4,4
Vishal,6,5,5,3,5,4,4,0,6,3,5,6,6,6,5,5,5,4,5
Francisco,3,4,4,5,4,4,5,6,0,4,5,5,6,4,5,4,5,3,5
Sam Celarek,4,4,3,4,3,4,5,3,4,0,5,6,6,4,4,3,5,4,3
Sky,5,3,5,3,3,4,2,5,5,5,0,6,6,2,3,4,4,4,4
Anastasia,5,5,4,4,4,4,5,6,5,6,6,0,5,5,5,4,4,3,5
Shoshannah Tekofsky,5,6,4,4,4,5,5,6,6,6,6,5,0,6,6,4,5,4,5
Jonathan Ray,3,3,4,4,3,4,2,6,4,4,2,5,6,0,4,3,4,4,3
Emmett,5,5,5,5,5,5,4,5,5,4,3,5,6,4,0,3,5,4,5
Samuel,4,3,3,3,3,3,4,5,4,3,4,4,4,3,3,0,4,2,4
Harold,4,4,5,5,4,4,4,5,5,5,4,4,5,4,5,4,0,4,4
Chris Watkins,5,3,3,3,3,2,4,4,3,4,4,3,4,4,4,2,4,0,4
Max,3,4,3,3,2,3,4,5,5,3,4,5,5,3,5,4,4,4,0

In [7]:
def max_pair(distance_matrix):
    player1 = distance_matrix.max().idxmax()
    player2 = distance_matrix.drop(player1).idxmax()[player1]
    
    return(player1, player2)

In [8]:
def greedy_sort(distance_matrix):
    
    sorted_pairs = []
    
    dm = distance_matrix.copy()
    
    while dm.columns.size > 1:
        a, b = max_pair(dm)

        sorted_pairs.append((a, b))

        dm.drop([a, b], inplace=True, axis='columns')
        dm.drop([a, b], inplace=True, axis='index')
        
    if dm.columns.size > 0:
        sorted_pairs.append(dm.max().idxmax())
        
    return sorted_pairs

In [9]:
greedy_sort(dm)

[('Priyansha', 'Vishal'),
 ('Silas', 'Shoshannah Tekofsky'),
 ('Sam Celarek', 'Anastasia '),
 ('Maia', 'Kayla'),
 ('Søren Elverlin ', 'Francisco'),
 ('Roger Curley', 'Emmett'),
 ('Phil', 'Sky'),
 ('Jonathan Ray', 'Harold'),
 ('Samuel', 'Max'),
 'Chris Watkins']

In [10]:
print('\n'.join(str(p) for p in greedy_sort(dm)))

('Priyansha', 'Vishal')
('Silas', 'Shoshannah Tekofsky')
('Sam Celarek', 'Anastasia ')
('Maia', 'Kayla')
('Søren Elverlin ', 'Francisco')
('Roger Curley', 'Emmett')
('Phil', 'Sky')
('Jonathan Ray', 'Harold')
('Samuel', 'Max')
Chris Watkins